### ISSUE TITLE
[BUG] User search functionality

### ISSUE THREAD

**Issue by RiinaLi** [buerokratt/Buerokratt-Chatbot#1013] opened 2024-11-19 08:50 UTC
**Bug description:**
In the Administartion -Users module table search, the search functionality only works within the data displayed on the current page. For example, if a user’s name is on another page, the search does not return any results. Same in Chats - Active chats - Assign to another CSA, name search.

**Expected behavior:**
The search should function across the entire list of users, regardless of the number of pages.

Screenshots:
![Image](https://github.com/user-attachments/assets/0af51203-ae23-4d47-a294-0c15d3449d49)
![Image](https://github.com/user-attachments/assets/b9bc8364-faf2-459a-a095-064bc64e4d3c)

**Additional information:**
This issue limits the usability of search, especially when the user list spans multiple pages.

**Comment by ffrose** [comment] 2024-12-05 07:37
As of right now, User search functionality seems to be disabled entirely. Search should work whether or not user is online.

![Image](https://github.com/user-attachments/assets/043dc94b-91b1-43ec-9326-aae334381be9)

**Comment by IgorKrupenja** [comment] 2024-12-05 11:21
@ffrose This was a deployment issue we just fixed on call with Varmo. Please test again, it seems to be working now.

**Comment by jaX10bt** [comment] 2024-12-12 07:37
Works as intended

**Closed by jaX10bt** 2024-12-12 07:37 UTC
Labels: bug, v2.0.2
