### ISSUE TITLE
[BUG] Users table GUI fixes

### ISSUE THREAD

**Issue by jaX10bt** [buerokratt/Buerokratt-Chatbot#972] opened 2024-11-05 10:47 UTC
**Bug description:**
Users table in /chat/users has pagination even when filtering the list to have fewer than one page of users.
Also when the card is filtered to have no visible users, the search input dropdown makes the card scrollable.

**Expected behavior:**
Pagination numbers update accordingly when filtering the users table.
Search input dropdown stays on top of the card without making the card scrollable.

**Screenshots:**
https://github.com/user-attachments/assets/8496ea82-0eb3-440b-80a4-46ae54debc10

**Comment by 1AhmedYasser** [comment] 2024-11-15 16:29
The PR here fixes Pagination numbers update accordingly when filtering the users table.

but Search input dropdown stays on top of the card without making the card scrollable. should be fixed here https://github.com/buerokratt/Buerokratt-Chatbot/issues/974

**Comment by ffrose** [comment] 2024-11-21 11:39
Working as intended.

**Closed by ffrose** 2024-11-21 11:39 UTC
Labels: bug, v2.0.2
